### ISSUE TITLE
The relative positioning of the dropdown component is restrictive

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/rendition#301]
The relative positioning of the DropDownComponent restricts the drop down list when an ancestor has set overflow:
![screen shot 2018-01-16 at 19 00 22-fullpage](https://user-images.githubusercontent.com/1295829/35001644-d4d259bc-faef-11e7-9e3f-2e84325ed4e8.png)
In the above case the table container has `overflow-x: auto` and the drop down list can't be rendered outside of it.

Changing the positioning of the wrapper to static and using transforms for the menu would fix the issue.
Would it make sense to add properties for setting custom styles on the wrapper and the menu?

**Comment by LucianBuzzo** [comment]
I'd be interested to see a PR with the changes you propose, I'm hesitant to introduce complicated positioning logic to an otherwise simple component.
