### ISSUE TITLE
Add BadgeSelect component

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/rendition#323]
![screen shot 2018-01-23 at 15 18 46](https://user-images.githubusercontent.com/15064535/35283636-b9d958ac-0050-11e8-9bb7-0a8a2b766977.png)

**Comment by thgreasi** [comment]
Do we really need a separate component for this?
Can't we just compose it?

**Comment by LucianBuzzo** [comment]
@thgreasi This pattern is getting used all over the dashboard for multicontainer. The implementation there is composed, but complex enough that I thought it would be worth abstracting to rendition.

**Comment by thgreasi** [comment]
Sounds sensible :+1:
