### ISSUE TITLE
Navbar crashes if it only contains a single link

### ISSUE THREAD

**Issue by jviotti** [resin-io-modules/rendition#329]
<img width="1062" alt="screen shot 2018-01-25 at 12 38 00 pm" src="https://user-images.githubusercontent.com/2192773/35400362-eaed962e-01cc-11e8-8c1f-1ec7a68cbc37.png">

**Comment by amdomanska** [comment]
I cannot reproduct the issue,

**Comment by LucianBuzzo** [comment]
Ah @amdomanska I think this issue is a duplicate, as the bug was already fixed in this PR https://github.com/resin-io-modules/rendition/pull/532
I'll close this issue.
