### ISSUE TITLE
Limit BadgeSelect size

### ISSUE THREAD

**Issue by dimitrisnl** [resin-io-modules/rendition#410]
Relates to: https://github.com/resin-io/resin-ui/issues/1942

Reproduced: 
[![Edit 48xz8wr1mw](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/48xz8wr1mw)

**Comment by dimitrisnl** [comment]
@LucianBuzzo Would love to hear your opinion on this one. 

Apps with lots of services create some issues, but you can only do so much with a simple dropdown.

**Comment by LucianBuzzo** [comment]
@dimitrisnl Limit the menu height to 280px, and set `overflow-y: auto` on the menu
