### ISSUE TITLE
Add Card component

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/rendition#431]
The `box-shadow` should be `0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2)`.
See: https://www.flowdock.com/app/rulemotion/resin-frontend/threads/7YsQn5uXJCydF9Bbh_rJKMUqBpC
See: https://app.zeplin.io/project/59cbb35a8edcbe2d8fbe5678/screen/59d4f58a68cf621d3adab6e5

**Comment by dimitrisnl** [comment]
Simple card? No header?

**Comment by thgreasi** [comment]
Ideally all the variants of it + the one with lines as found in the billing page for the invoices.

**Comment by dimitrisnl** [comment]
Gotcha
