### ISSUE TITLE
navbar causing breakpoints issue

### ISSUE THREAD

**Issue by deesims** [resin-io-modules/rendition#508]
getting some breakpoints error when trying to render Navbar component

`class App extends Component {

    render() {
        const Brand = (
            <Link color='white' href={'/'}>
                <Img style={{ height: '20px' }} src={logo} />
            </Link>
        )
        return (
            <div className="App">
        <Container>
                <Navbar brand={Brand} color='white'>
                    <Link color='white' href={'/docs/'}>
                        Docs
                    </Link>
                    <Link color='white' href={'/changelog/'}>
                        changelog
                    </Link>
                    <Link color='white' href={'/gitter/'}>
                        gitter
                    </Link>
                </Navbar>
            </Container>

                <div className={'center'} style={{display: 'flex',  justifyContent:'center', alignItems:'center', height: '20vh'}}>
                <Img color='white' minHeight={'250px'} src={bgImage}>
                </Img>
                </div>

                <Home/>
                <Divider color='#ccc' />

            </div>
        );`
![screenshotatuploadcc_1532076237634](https://user-images.githubusercontent.com/17972101/42992802-9fbb726c-8bd7-11e8-9759-0d6a42129b58.png)

Linux Mint Distro

`{
  "name": "bright-state",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "rc-slider": "^8.6.1",
    "react": "^16.4.1",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^16.4.1",
    "react-rangeslider": "^2.2.0",
    "react-scripts": "1.1.4",
    "rendition": "^4.18.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}`

Perhaps I am not rendering properly ?

**Comment by LucianBuzzo** [comment]
@deesims The `Provider` component provides a `theme` property to its children, allowing us to provide constant values like colours, font sizes and border-radius for components. This is briefly mentioned in the README and shown in the usage section, but it's not explicitly mentioned that its required. I've updated the README file to emphasise that the `Provider` component needs to be used.
Storybook (the module we use for the interactive demo) is configured to wrap each story in the `Provider` component from a single config file here : https://github.com/resin-io-modules/rendition/blob/master/.storybook/config.js#L21
Your feedback highlights that this means that the stories we link to don't provide a comprehensive example of how to use a component, so I'm going to open an issue to have the `Provider` component present in each of the story files.
