### ISSUE TITLE
Error on console for Select tag element

### ISSUE THREAD

**Issue by Rahul-Sagore** [resin-io-modules/rendition#514]
**Describe the bug**
Getting error on console for Select tag element
```
Uncaught TypeError: Cannot read property '4' of undefined
    at eval (Select.js:33)
```

**To Reproduce**
1. Taken select code from https://github.com/resin-io-modules/rendition/blob/master/src/stories/Select.js
2. Code:
```js
import React from 'react'
import { Select } from 'rendition'

const SelectComponent = props => {
	return (
    	<Select>
          <option value={1} key={1}>Option 1</option>
        </Select>
    )
}
export default SelectComponent
```
3. Reload the page
4. See error on devtool console tab

**Expected behavior**
Should render Select box, should not give error

**Specifications (please complete the following information):**
  - Browser: Chrome
  - OS: OSX 10.11.2
  - Environment: devenv

**Screenshot**
Accessing theme element, while theme is empty object

<img width="944" alt="screen shot 2018-07-22 at 4 53 26 pm" src="https://user-images.githubusercontent.com/3587851/43045092-e001a022-8dcf-11e8-8ae2-a6c2ec9fab85.png">

**Comment by LucianBuzzo** [comment]
@Rahul-Sagore Are you wrapping your app in the `Provider` component?

**Comment by Rahul-Sagore** [comment]
@LucianBuzzo No, using simple React Component. The code mentioned in above description is what I have. I am able to use other components (Input, Dropdown, Table). But Select is breaking.

**Comment by LucianBuzzo** [comment]
@Rahul-Sagore You need to wrap your entire react application in the `Provider` component so that rendition components can correctly inherit the `theme` property, see my comment here for more detail https://github.com/resin-io-modules/rendition/issues/508#issuecomment-406983002

**Comment by thgreasi** [comment]
@Rahul-Sagore did wrapping your components with a `<Provider>` fix the issue?
Should we close this?

**Comment by Rahul-Sagore** [comment]
Thanks, it is working now. 

I had followed the documentation on https://resin-io-modules.github.io/.
From there I saw Select example on: [stories/Select.js](https://github.com/resin-io-modules/rendition/blob/master/src/stories/Select.js) and there was no info about using `Provider`. Other people also might get confused. Need to change documentation/Examples if possible.

**Comment by thgreasi** [comment]
Linking to #516 for the `<Provider>` part in the stories and closing for now.
