### ISSUE TITLE
Navbar component breaks when enclosing only one direct child component.

### ISSUE THREAD

**Issue by facundobringas** [resin-io-modules/rendition#524]
**Describe the bug**
Navbar component breaks when enclosing only one direct child component.

**To Reproduce**
Include a Navbar containing one child component. Eg. Copy the Navbar story code and remove Brand and Links in order to leave only one direct child component : 

` <Navbar color='white'>
        <Link color='white' href={'/docs/'}>
          Docs
        </Link>
  </Navbar>`

**Expected behavior**
It should render succesfully.

**Screenshots**
Navbar is not rendered at all and console prints the following error:
![image](https://user-images.githubusercontent.com/10635919/43111909-c9f9432a-8ec9-11e8-9f1a-c9cd8165b684.png)

**Specifications (please complete the following information):**
  - Browser: Chrome 67  whatsmybrowser.org/b/52G5VWD
  - OS: Ubuntu 16.04 LTS
  - Environment: development (webpack-dev-server --mode development)

**Additional context**
When added another direct child component Navbar renders normally:

` <Navbar color="white">
      <Link color="white" href="/docs/">
        Docs
      </Link>
      <Link color="white" href="/changelog/">
        changelog
      </Link>
  </Navbar>`

I ran into this error when trying to enclose Navbar child components inside the recently documented Flex container.

**Comment by thgreasi** [comment]
Hey, thanks for the report, I will take a look at it soon.

**Comment by thgreasi** [comment]
Oh nevermind, I just saw #532 :)
