### ISSUE TITLE
ProgressBar: Should allow setting custom colors

### ISSUE THREAD

**Issue by thgreasi** [resin-io-modules/rendition#538]
**Is your feature request related to a problem? Please describe.**
We need this for the DeviceProgress componet, so that the ProgressBar color matches that of the device status icon.

**Describe the solution you'd like**
It would be great to add the `color` and `background` to the typings of the ProgressBar, since this already works.

**Comment by LucianBuzzo** [comment]
@thgreasi Can we close this issue now that your PR is merged?

**Comment by thgreasi** [comment]
Absolutely, it seems that I used `Connects-to` instead of `Resolves`...
