### ISSUE TITLE
highlightedRows prop not working on Table Component

### ISSUE THREAD

**Issue by tobzy** [resin-io-modules/rendition#550]
**Describe the bug**
I used the Table component with the highlightedRows prop and it didn't work as expected. No Rows were highlighted.

**Usage
<img width="648" alt="screen shot 2018-08-13 at 4 27 58 pm" src="https://user-images.githubusercontent.com/18688618/44041903-d56cbd56-9f16-11e8-8782-4eaf8260f1e3.png">

**Expected behavior**
The highlighted rows should have a light blue background like in the image below.
<img width="1115" alt="screen shot 2018-08-13 at 4 33 41 pm" src="https://user-images.githubusercontent.com/18688618/44041871-bc5e4a46-9f16-11e8-98fc-3a9742401e73.png">

**Comment by LucianBuzzo** [comment]
@tobzy Which version of rendition are you using?

**Comment by LucianBuzzo** [comment]
I can't replicate this issue, my suspicion is that this bug was due to using an older version of rendition that didn't support `highlightedRows`.
