### ISSUE TITLE
Tables: Expose a method to clear selected rows

### ISSUE THREAD

**Issue by dimitrisnl** [resin-io-modules/rendition#560]

**Comment by LucianBuzzo** [comment]
@dimitrisnl I think using `ref` is the correct approach. This is how libraries like `react-virtualized` do it and I think it makes sense. A prop based approach will quickly become overly complicated and potentially lead to confusion for users.
Let's review the `Table` code and ensure that there is a semantic method for setting/removing selected rows and make it properly documented.
