### ISSUE TITLE
Table crashes if data prop is null

### ISSUE THREAD

**Issue by LucianBuzzo** [resin-io-modules/rendition#589]

**Comment by dimitrisnl** [comment]
@LucianBuzzo Can you give me a little bit more context? Did you notice it in any project or the storybook? The latest merged PR should revert the functionality as it was before having the Pager included.

**Comment by LucianBuzzo** [comment]
@dimitrisnl Heres a sandbox showing the issue https://codesandbox.io/s/ymlqxx83yj

**Comment by LucianBuzzo** [comment]
It should just degrade gracefully if the data property is not an array
